In [96]:
import pandas as pd
corpus = pd.read_csv("../csv/cleaned_svevo_dataset_ITA _with_sentiment.csv")
corpus["date"] = pd.to_datetime(corpus["date"], format="%d/%m/%Y", errors='coerce' )
corpus.head()

,Unnamed: 0,Unnamed: 0.1,X,letter_number,pair,index,date,year,sender,senderLocation,...,text,tokens,doc,lemmatized_tokens,anger,fear,joy,sadness,positive,negative
0,0,0,17,18,Svevo Joyce,18,1928-03-27,1928,Ettore Schmitz,Trieste,...,"Trieste, li 27 Marzo 1928 Caro amico, Qui ho t...",trieste marzo caro amico trovare lette...,trieste marzo caro amico trovato lettere ...,trieste marzo caro amico trovare lette...,0,0,78,22,89,11
1,1,1,20,21,Svevo Larbaud,2,1925-01-15,1925,Ettore Schmitz,Trieste,...,"Trieste 10 Villa Veneziani, 15 Gennaio 1925 Es...",trieste villa veneziano gennaio esimio signore...,trieste villa veneziani gennaio esimio signore...,trieste villa veneziano gennaio esimio signore...,4,4,38,54,46,54
2,2,2,21,22,Svevo Larbaud,3,1925-02-16,1925,Ettore Schmitz,Trieste,...,Villa Veneziani Trieste 10. 16.2.1925 Esimio S...,villa veneziano trieste esimio signore caro...,villa veneziani trieste esimio signore cara ...,villa veneziano trieste esimio signore caro...,18,9,45,27,36,64
3,3,3,27,28,Svevo Larbaud,9,1925-09-15,1925,Ettore Schmitz,Trieste,...,Villa Veneziani Trieste 10 15 Settembre 1925 E...,villa veneziano trieste settembre esimio car...,villa veneziani trieste settembre esimio caro...,villa veneziano trieste settembre esimio car...,17,4,35,43,43,57
4,4,4,38,39,Svevo Crémieux,5,1926-08-02,1926,Ettore Schmitz,Tarasp,...,"Vulpera Tarasp, [2] Agosto 1926 Carissimo amic...",vulpera tarasp agosto caro amico mille grazia ...,vulpera tarasp agosto carissimo amico mille gr...,vulpera tarasp agosto caro amico mille grazia ...,0,0,69,31,69,31

In [97]:
corpus["date"]

0     1928-03-27
1     1925-01-15
2     1925-02-16
3     1925-09-15
4     1926-08-02
         ...
510   1928-04-12
511   1928-04-19
512   1928-07-07
513   1928-07-09
514   1928-07-24
Name: date, Length: 515, dtype: datetime64[ns]

In [86]:
x=corpus.groupby(pd.Grouper(key='date', freq='Y')).count()
x["Unnamed: 0"]
y=corpus.groupby(pd.Grouper(key='date', freq='Y')).sum()
y[""]
#y = y[["date","anger","fear", "joy", "sadness", "positive", "negative"]]

,Unnamed: 0,Unnamed: 0.1,X,letter_number,index,year,anger,fear,joy,sadness,positive,negative
date,,,,,,,,,,,,
1895-12-31,350,350,833,838,28,9475,59,27,169,243,206,294
1896-12-31,1133,1133,2556,2570,176,26544,127,33,644,595,604,796
1897-12-31,756,756,1581,1589,37,15176,265,33,203,300,162,638
1898-12-31,2575,2575,5085,5108,416,43654,467,134,683,1013,639,1661
1899-12-31,1841,1841,3640,3654,238,26586,242,56,439,665,475,925
1900-12-31,2655,2655,5235,5253,357,34200,220,115,571,894,602,1198
1901-12-31,7678,7678,14882,14925,1681,81743,603,186,1482,2027,1422,2878
1902-12-31,822,822,1581,1585,21,7608,33,34,144,190,157,243
1903-12-31,10952,10952,20486,20533,1592,89441,544,162,1812,2182,1818,2882
1904-12-31,2893,2893,5248,5259,89,20944,119,88,443,449,429,671
1905-12-31,3318,3318,5986,5998,166,22860,117,24,517,540,482,718
1906-12-31,2583,2583,4746,4755,147,17154,109,24,367,397,386,514
1907-12-31,1470,1470,2727,2732,27,9535,45,17,247,192,196,304
1908-12-31,12324,12324,22690,22729,1279,74412,436,125,1543,1795,1622,2278
1909-12-31,2031,2031,3697,3703,29,11454,66,12,219,302,184,416
1910-12-31,5592,5592,10141,10157,234,30560,286,45,500,772,524,1076
1911-12-31,8497,8497,15348,15371,467,43953,302,119,744,1134,843,1457
1912-12-31,3084,3084,5570,5578,58,15296,98,34,347,320,341,459
1913-12-31,21180,21180,37394,37445,1643,97563,640,275,1799,2385,1923,3177
1914-12-31,3115,3115,5445,5452,56,13398,62,35,256,345,255,445
1915-12-31,2255,2255,4035,4040,15,9575,73,23,197,206,207,293
1916-12-31,0,0,0,0,0,0,0,0,0,0,0,0
1917-12-31,0,0,0,0,0,0,0,0,0,0,0,0
1918-12-31,1365,1365,2433,2436,6,5754,53,7,86,154,89,211
1919-12-31,457,457,813,814,1,1919,12,0,18,71,29,71
1920-12-31,0,0,0,0,0,0,0,0,0,0,0,0
1921-12-31,458,458,814,815,1,1921,6,0,41,53,41,59
1922-12-31,3234,3234,5730,5737,32,13454,104,37,244,315,263,437
1923-12-31,0,0,0,0,0,0,0,0,0,0,0,0
1924-12-31,1874,1874,3322,3326,17,7696,27,15,191,166,187,213
1925-12-31,2390,2390,4351,4361,73,19250,105,29,417,447,476,524
1926-12-31,8271,8271,15581,15617,943,69336,451,151,1494,1503,1535,2065
1927-12-31,5499,5499,10707,10739,1123,61664,420,82,1386,1310,1348,1852
1928-12-31,4153,4153,7898,7921,426,44344,233,61,1239,768,1228,1072

In [104]:
corpus.shape

(515, 24)

In [55]:
corpus["fear"][68]

9

In [49]:
display(corpus)

,Unnamed: 0,Unnamed: 0.1,X,letter_number,pair,index,date,year,sender,senderLocation,...,text,tokens,doc,lemmatized_tokens,anger,fear,joy,sadness,positive,negative
0,0,0,17,18,Svevo Joyce,18,1928-03-27,1928,Ettore Schmitz,Trieste,...,"Trieste, li 27 Marzo 1928 Caro amico, Qui ho t...",trieste marzo caro amico trovare lette...,trieste marzo caro amico trovato lettere ...,trieste marzo caro amico trovare lette...,0,0,78,22,89,11
1,1,1,20,21,Svevo Larbaud,2,1925-01-15,1925,Ettore Schmitz,Trieste,...,"Trieste 10 Villa Veneziani, 15 Gennaio 1925 Es...",trieste villa veneziano gennaio esimio signore...,trieste villa veneziani gennaio esimio signore...,trieste villa veneziano gennaio esimio signore...,4,4,38,54,46,54
2,2,2,21,22,Svevo Larbaud,3,1925-02-16,1925,Ettore Schmitz,Trieste,...,Villa Veneziani Trieste 10. 16.2.1925 Esimio S...,villa veneziano trieste esimio signore caro...,villa veneziani trieste esimio signore cara ...,villa veneziano trieste esimio signore caro...,18,9,45,27,36,64
3,3,3,27,28,Svevo Larbaud,9,1925-09-15,1925,Ettore Schmitz,Trieste,...,Villa Veneziani Trieste 10 15 Settembre 1925 E...,villa veneziano trieste settembre esimio car...,villa veneziani trieste settembre esimio caro...,villa veneziano trieste settembre esimio car...,17,4,35,43,43,57
4,4,4,38,39,Svevo Crémieux,5,1926-08-02,1926,Ettore Schmitz,Tarasp,...,"Vulpera Tarasp, [2] Agosto 1926 Carissimo amic...",vulpera tarasp agosto caro amico mille grazia ...,vulpera tarasp agosto carissimo amico mille gr...,vulpera tarasp agosto caro amico mille grazia ...,0,0,69,31,69,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,510,510,882,883,Svevo Prezzolini,13,1928-04-12,1928,Ettore Schmitz,Trieste,...,"A Giuseppe Prezzolini Villa Veneziani, Trieste...",giuseppe prezzolini villa veneziano trieste ...,giuseppe prezzolini villa veneziani trieste a...,giuseppe prezzolini villa veneziano trieste ...,0,0,75,25,67,33
511,511,511,883,884,Svevo Rusconi Besso,14,1928-04-19,1928,Ettore Schmitz,Trieste,...,"A Bice Rusconi Besso Villa Veneziani, Trieste,...",bice rusconi besso villa veneziano trieste a...,bice rusconi besso villa veneziani trieste ap...,bice rusconi besso villa veneziano trieste a...,16,0,29,55,26,74
512,512,512,887,888,Svevo Rossi,24,1928-07-07,1928,Ettore Schmitz,Trieste,...,Ad Alberto Rossi Ella indovinò: il mio success...,alberto rosso indovin successo tutt ...,alberto rossi indovin successo tutt gran...,alberto rosso indovin successo tutt ...,0,0,80,20,80,20
513,513,513,888,889,Svevo Pasini,25,1928-07-09,1928,Ettore Schmitz,Trieste,...,"A Ferdinando Pasini Trieste, 9 Luglio 1928 Pr...",ferdinando pasini trieste luglio pregiato si...,ferdinando pasini trieste luglio pregiatissim...,ferdinando pasini trieste luglio pregiato si...,14,0,71,14,57,43
514,514,514,891,892,Svevo Pasini,28,1928-07-24,1928,Ettore Schmitz,Trieste,...,"A Ferdinando Pasini Trieste, 24 Luglio 1928 C...",ferdinando pasini trieste luglio caro profes...,ferdinando pasini trieste luglio carissimo pr...,ferdinando pasini trieste luglio caro profes...,12,0,50,38,50,50